import { Schema } from "../../../amplify/data/resource";

type Keyword = Schema["Keyword"]["type"];
export const getStageAndButtonText = (keyword: Keyword) => {
  if (!keyword?.preOutlineStartApproval)
    return { stage: "Pre-Outline", buttonText: "Generate Pre-Outline" };
  if (!keyword?.preOutlineAutoGenerated)
    return { stage: "Pre-Outline", buttonText: "Generating Pre-Outline..." };
  if (!keyword?.approvedTitle)
    return { stage: "Pre-Outline", buttonText: "Select Title" };
  if (!keyword?.preOutlineResultApproved)
    return { stage: "Pre-Outline", buttonText: "Approve Pre-Outline" };

  if (!keyword?.outlineStartApproval)
    return { stage: "Outline", buttonText: "Generate Outline" };
  if (!keyword?.outlineAutoGenerated)
    return { stage: "Outline", buttonText: "Generating Outline..." };
  if (!keyword.outlineResultApproved)
    return { stage: "Outline", buttonText: "Review Outline" };
  if (!keyword?.draftGenerated)
    return { stage: "Draft", buttonText: "Generate Draft" };
  if (!keyword?.draftApproved)
    return { stage: "Draft", buttonText: "Approve Draft" };
  if (!keyword?.marketingInfoStartApproval)
    return { stage: "SEO", buttonText: "Generate SEO Info" };
  if (!keyword?.marketingInfoAutoGenerated)
    return {
      stage: "Marketing Info",
      buttonText: "Generating Marketing Info...",
    };
  if (!keyword?.marketingInfoResultApproved)
    return { stage: "Marketing Info", buttonText: "Approve Marketing Info" };
  if (!keyword?.socialsInfoStartApproval)
    return { stage: "Socials", buttonText: "Generate Socials" };
  if (!keyword.socialsInfoAutoGenerated)
    return {
      stage: "Socials Info",
      buttonText: "Generating Socials Info...",
    };
  if (!keyword?.socialsInfoResultApproved)
    return { stage: "Socials Info", buttonText: "Approve Socials Info" };
  if (!keyword?.evalStartApproval)
    return { stage: "Evaluation", buttonText: "Generate Evaluation" };
  if (!keyword?.evalAutoGenerated)
    return { stage: "Evaluation", buttonText: "Generating Evaluation..." };
  if (!keyword?.evalResultApproved)
    return { stage: "Evaluation", buttonText: "Approve Evaluation" };
  return { stage: "Complete", buttonText: "Process Complete" };
};
